# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ca729d405450071458a9a760690792d0eb9ab4302b8b98487c045e1d4083103d0000de58eb01faa75837e758e526e45c1b9397877ccef43887ae65be83c4b06

test:
  secret_key_base: e5f5a657780a705993387866e4e7bcbc996e4c4cca71e4f006547d28b785c62a6e2b60bc596f717b89d88638c3e15ff39f2173beca98f3b5b26955bb128bed22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
